batch_size: 16
warmup_steps: 0.01
after_norm: 1
model_type: 'transformer'
normalize_embed: True
dropout: 0.15
fc_dropout: 0.4
pos_embed: null
encoding_type: 'bioes'
device: 0
ignore_cache: false

model_ids:
  tener: 'TENER'